[package]
name = "fdpm"
version = "1.0.1"
edition = "2024"
license = "MIT"
description = "fully deterministic password manager (fdpm) deniable and metadata free password manager. which doesn't care for backups nor metadata"
repository = "https://github.com/unamed01/fdpm.git"
readme = "README.md"
categories = ["cryptography", "security"]

[dependencies]
rand = "0.10.2"
zeroize = "1.9.0"
argon2 = "0.5.3"
rpassword = "7.5.4"
arboard = { version = "3.6.1", default-features = false }
ctrlc = "3.5.2"
